config/routes.rb
Frab::Application.routes.draw do

  scope "(:locale)" do

    resource :session

    match "/conferences/new" => "conferences#new", as: "new_conference"
    match "/conferences" => "conferences#create", as: "create_conference", via: :post
    match "/conferences" => "conferences#index", as: "conference_index", via: :get
    match "/conferences" => "conferences#destroy", via: :delete

    resources :people do
      resource :user
      member do
        put :attend
      end
    end

    scope path: "/:conference_acronym" do

      namespace :public do
        match "/schedule" => "schedule#index", as: "schedule_index"
        match "/schedule/style" => "schedule#style", as: "schedule_style"
        match "/schedule/:day" => "schedule#day", as: "schedule"
        match "/events" => "schedule#events", as: "events"
        match "/events/:id" => "schedule#event", as: "event"
        match "/speakers" => "schedule#speakers", as: "speakers"
        match "/speakers/:id" => "schedule#speaker", as: "speaker"

        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do

        resource :session

        resource :user do 
          resource :password
          resource :confirmation
        end

        resource :person do
          resource :availability
        end

        match "/events/:id/confirm/:token" => "events#confirm", as: "event_confirm_by_token"

        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end

        match "/open_soon" => "welcome#open_soon", as: "open_soon"
        match "/not_existing" => "welcome#not_existing", as: "not_existing"

        root to: "people#show"

      end # namespace :cfp

      match "/recent_changes" => "recent_changes#index", as: "recent_changes"

      match "/schedule.pdf" => "schedule#custom_pdf", as: "schedule_custom_pdf", defaults: {format: :pdf}
      match "/schedule" => "schedule#index", as: "schedule"
      match "/schedule/update_track" => "schedule#update_track", as: "schedule_update_track"
      match "/schedule/update_event" => "schedule#update_event", as: "schedule_update_event"
      match "/schedule/new_pdf" => "schedule#new_pdf", as: "new_schedule_pdf"
      match "/schedule/html_exports" => "schedule#html_exports"
      match "/schedule/create_static_export" => "schedule#create_static_export", via: :post
      match "/schedule/download_static_export" => "schedule#download_static_export"

      match "/statistics/events_by_state" => "statistics#events_by_state", as: "events_by_state_statistics"
      match "/statistics/language_breakdown" => "statistics#language_breakdown", as: "language_breakdown_statistics"
      match "/statistics/gender_breakdown" => "statistics#gender_breakdown", as: "gender_breakdown_statistics"

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
        get :edit_ticket_server
      end

      resource :call_for_papers do
        get :edit_notifications
      end
      match "/call_for_papers/default_notifications" => "call_for_papers#default_notifications", as: "call_for_papers_default_notifications"

      resources :people do
        resource :user
        resource :availability
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
        end
        resource :event_rating
        resources :event_feedbacks
      end

      match "/reports" => "reports#index", as: "reports"
      match "/reports/on_people/:id" => "reports#show_people", as: "report_on_people"
      match "/reports/on_events/:id" => "reports#show_events", as: "report_on_events"
      match "/reports/on_statistics/:id" => "reports#show_statistics", as: "report_on_statistics"

      resources :tickets do
        member do
          post :create
        end
      end

    end # scope path: "/:conference_acronym"

    match "/:conference_acronym" => "home#index", as: "conference_home"
    root to: "home#index"

  end # scope "(:locale)" do

  root to: "home#index"

end

app/views/shared/_availabilities_form.html.haml
= javascript_include_tag "moment.min"

= semantic_form_for(person, :url => url) do |f|
  = f.inputs do
    - conference.days.each do |day|
      - availability = availabilities.select{ |a| a.day == day }.first
      - availability.nil? and availability = Availability.new(:day => day, :conference => conference)
      = render(:partial => 'shared/availabilities_slider', :locals => { :f => f, :day => day, :availability => availability })
  = f.buttons do
    - if can? :crud, person
      = f.commit_button t("cfp.save_availability"), :button_html => {:class => "btn primary"}

:javascript
  $(function() {

    SliderForm = {
      initialize: function(options) {
        var id                = options.id;
        var model_id          = options.id - 1;
        this.utc_offset       = options.utc_offset / 60 * -1;
        var checkbox          = $('span#day_'+id+' input[type="checkbox"].cbx')
        var time_range_slider = $('span#day_'+id+' .time_range_slider');

        // setup checkbox event
        SliderForm._setup_checkbox(id);
        SliderForm._setup_slider(id);

        // initial state
        var test = time_range_slider.data("from")
        if( test && test > 0 ) {
          checkbox.attr('checked', true);
          SliderForm.set_on(id);
        } else {
          checkbox.attr('checked', false);
          SliderForm.set_off(id);
        }

      },

      _setup_checkbox: function(id) {
        $('span#day_'+id+' input[type="checkbox"].cbx').change(function() { 
          if( $(this).attr('checked') )
            SliderForm.set_on(id);
          else
            SliderForm.set_off(id);
        });
      },

      _setup_slider: function(id) {
        var el_slider      = $('span#day_'+id+' .time_range_slider');
        el_slider.slider({
          range: true,
          step: 15*60,
          min: el_slider.data("min"),
          max: el_slider.data("max"),
          values: [el_slider.data("from"), el_slider.data("to")],
          slide: function(event, ui) {
            var dates = [SliderForm.get_date_string(ui.values[0]), 
                         SliderForm.get_date_string(ui.values[1])];
            SliderForm.update_date_labels(id, dates);
            SliderForm.update_hidden_inputs(id, dates);
          }
        });
      },

      get_date_string: function(unix) {
        var date_format = 'YYYY-MM-DD HH:mm';
        return moment.utc(unix * 1000).zone(this.utc_offset).format(date_format);
      },

      update_date_labels: function(id,values) {
        var el_start_label = $('span#day_'+id+' .start_date');
        var el_end_label   = $('span#day_'+id+' .end_date');
        el_start_label.html(values[0]);
        el_end_label.html(values[1]);
      },

      update_hidden_inputs: function(id,values) {
        var el_inputs = $('span#day_'+id+' input');
        el_inputs.eq(0).val(values[0]);
        el_inputs.eq(1).val(values[1]);
      },

      update_slider_values: function(id,values) {
        var el_slider = $('span#day_'+id+' .time_range_slider');
        el_slider.slider("values",0, values[0]);
        el_slider.slider("values",1, values[1]);
      },

      set_slider_state: function(id,state) {
        var el_slider = $('span#day_'+id+' .time_range_slider');
        $('span#day_'+id+' .time_range_slider').slider(state);
      },

      set_on: function(id) {
        var el_slider = $('span#day_'+id+' .time_range_slider');
        var el_inputs = $('span#day_'+id+' input');
        if(el_inputs.eq(0).val()<0) {
          var min = el_slider.data("min");
          var max = el_slider.data("max");
          // missing values, use min/max as default
          SliderForm.update_slider_values(id, [min,max]);
          var dates = [SliderForm.get_date_string(min), 
                       SliderForm.get_date_string(max)];
          SliderForm.update_date_labels(id, dates);
          SliderForm.update_hidden_inputs(id, dates);
        } else {
          var from  = el_slider.data("from");
          var to    = el_slider.data("to");
          var dates = [SliderForm.get_date_string(from), 
                       SliderForm.get_date_string(to)];
          SliderForm.update_date_labels(id, dates);
        }
        SliderForm.set_slider_state(id, "enable");
      },

      set_off: function(id) {
        SliderForm.update_hidden_inputs(id, [-1,-1]);
        SliderForm.update_slider_values(id, [-1,-1]);
        SliderForm.update_date_labels(id, ['-','-']);
        SliderForm.set_slider_state(id, "disable");
      },
    };

  });
    
- conference.days.each do |day|
  :javascript
    $(function() {
      SliderForm.initialize({ id: #{day.id}, utc_offset: #{day.start_date.utc_offset} });
    });

app/views/shared/_availabilities_slider.html.haml
- day_id = "day_" + day.id.to_s 
%span{ :id => day_id }
  %h3
    from
    %span.start_date
      = l day.start_date, :format => :pretty_datetime
    to
    %span.end_date
      = l day.end_date, :format => :pretty_datetime

  = f.semantic_fields_for :availabilities, availability do |af|
    = af.input :start_date, :as => :hidden
    = af.input :end_date, :as => :hidden
    = af.input :conference_id, :as => :hidden
    = af.input :day_id, :as => :hidden
    %span
      .time_range_slider{"data-min" => day.start_date.to_i,
                         "data-max" => day.end_date.to_i,
                         "data-from" => availability.start_date.to_i,
                         "data-to" => availability.end_date.to_i}
    %span
      = check_box_tag "available for day #{day.label}", '1', false, :class => 'cbx'
    available

app/views/shared/_dynamic_association.html.haml
= f.inputs title do
  - if hint
    %div.input.help-block= hint
  %div{:class => association_name.to_s}
    = f.semantic_fields_for association_name do |association_form|
      = render association_name.to_s.singularize + "_fields", :f => association_form
    .links
      = add_association_link association_name, f, association_name

app/views/shared/_event_attachment_fields.html.haml
%div.nested-fields
  = f.inputs do
    - if f.object.new_record?
      = f.input :title
      = f.input :public, :as => :boolean, :hint => "Is this attachment visible to the public?"
      = f.input :attachment
    - else
      = f.input :title
      = f.input :public, :as => :boolean, :hint => "Is this attachment visible to the public?"
      %div.input
        = link_to f.object.attachment_file_name, f.object.attachment.url, style: 'float:left'
    = remove_association_link :event_attachment, f

app/views/shared/_flash.html.haml
.flash
  - flash.each do |type, message|
    %div{:class => "alert-message #{type == :notice ? "success" : type.to_s} fade in", "data-alert" => "alert"}
      %a.close{:href => "#"} × 
      %p= message

app/views/shared/_language_fields.html.erb
<div class="nested-fields">
  <%= f.inputs do %>
    <%= f.input :code, :as => :bootstrap_language, :label => t("activerecord.models.language"), :priority_languages => [:en, :es, :de], :include_blank => "" %>
    <%= remove_association_link :language, f %>
  <% end %>
</div>

app/views/shared/_link_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :title
    = f.input :url
    = remove_association_link :link, f

app/views/shared/_people_tabs.html.haml
%ul.tabs
  %li{class: active_class?(person_path(@person), edit_person_path(@person))}= link_to "Profile", @person
  - if can? :crud, @person.user or can? :administrate, User
    - if @person.user.nil?
      %li{class: active_class?(new_person_user_path(@person))}= link_to "User account", new_person_user_path(@person)
    - else
      %li{class: active_class?(person_user_path(@person), edit_person_user_path(@person))}= link_to "User account", person_user_path(@person)
  - if can? :create, @person
    - if @person.availabilities_in(@conference).count == 0
      %li{class: active_class?(new_person_availability_path(@person))}= link_to "Availability", new_person_availability_path(@person)
    - else
      %li{class: active_class?(edit_person_availability_path(@person))}= link_to "Availability", edit_person_availability_path(@person)
  %li{class: active_class?(feedbacks_people_path)}= link_to "Feedback", feedbacks_people_path(:id => @person.id)

app/views/shared/_search_and_table.html.haml
.row
  .span16
    = render 'shared/simple_search', :path => request.path
.row
  .span16
    - if collection.empty?
      %p Sorry, but your search yielded no results.
    - else  
      = render 'table', :collection => collection 
      = actions_bar do
        = will_paginate collection

app/views/shared/_simple_search.html.erb
<%= form_tag path, :method => :get do %>
  <p>Search:
    <%= text_field_tag :term, params[:term] %> <%= link_to "clear",  path %>
  </p>
<% end %>