config/routes.rb
Frab::Application.routes.draw do

  scope "(:locale)" do

    resource :session

    match "/conferences/new" => "conferences#new", as: "new_conference"
    match "/conferences" => "conferences#create", as: "create_conference", via: :post
    match "/conferences" => "conferences#index", as: "conference_index", via: :get
    match "/conferences" => "conferences#destroy", via: :delete

    resources :people do
      resource :user
      member do
        put :attend
      end
    end

    scope path: "/:conference_acronym" do

      namespace :public do
        match "/schedule" => "schedule#index", as: "schedule_index"
        match "/schedule/style" => "schedule#style", as: "schedule_style"
        match "/schedule/:day" => "schedule#day", as: "schedule"
        match "/events" => "schedule#events", as: "events"
        match "/events/:id" => "schedule#event", as: "event"
        match "/speakers" => "schedule#speakers", as: "speakers"
        match "/speakers/:id" => "schedule#speaker", as: "speaker"

        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do

        resource :session

        resource :user do 
          resource :password
          resource :confirmation
        end

        resource :person do
          resource :availability
        end

        match "/events/:id/confirm/:token" => "events#confirm", as: "event_confirm_by_token"

        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end

        match "/open_soon" => "welcome#open_soon", as: "open_soon"
        match "/not_existing" => "welcome#not_existing", as: "not_existing"

        root to: "people#show"

      end # namespace :cfp

      match "/recent_changes" => "recent_changes#index", as: "recent_changes"

      match "/schedule.pdf" => "schedule#custom_pdf", as: "schedule_custom_pdf", defaults: {format: :pdf}
      match "/schedule" => "schedule#index", as: "schedule"
      match "/schedule/update_track" => "schedule#update_track", as: "schedule_update_track"
      match "/schedule/update_event" => "schedule#update_event", as: "schedule_update_event"
      match "/schedule/new_pdf" => "schedule#new_pdf", as: "new_schedule_pdf"
      match "/schedule/html_exports" => "schedule#html_exports"
      match "/schedule/create_static_export" => "schedule#create_static_export", via: :post
      match "/schedule/download_static_export" => "schedule#download_static_export"

      match "/statistics/events_by_state" => "statistics#events_by_state", as: "events_by_state_statistics"
      match "/statistics/language_breakdown" => "statistics#language_breakdown", as: "language_breakdown_statistics"
      match "/statistics/gender_breakdown" => "statistics#gender_breakdown", as: "gender_breakdown_statistics"

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
        get :edit_ticket_server
      end

      resource :call_for_papers do
        get :edit_notifications
      end
      match "/call_for_papers/default_notifications" => "call_for_papers#default_notifications", as: "call_for_papers_default_notifications"

      resources :people do
        resource :user
        resource :availability
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
        end
        resource :event_rating
        resources :event_feedbacks
      end

      match "/reports" => "reports#index", as: "reports"
      match "/reports/on_people/:id" => "reports#show_people", as: "report_on_people"
      match "/reports/on_events/:id" => "reports#show_events", as: "report_on_events"
      match "/reports/on_statistics/:id" => "reports#show_statistics", as: "report_on_statistics"

      resources :tickets do
        member do
          post :create
        end
      end

    end # scope path: "/:conference_acronym"

    match "/:conference_acronym" => "home#index", as: "conference_home"
    root to: "home#index"

  end # scope "(:locale)" do

  root to: "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!
  before_filter :not_submitter!

  def index
    if Conference.count == 0
      return redirect_to new_conference_path
    end
    if cannot? :read, Conference
      # maybe a crew user tries to login to the wrong conference?
      if current_user.is_crew?
        conference = current_user.conference_users.map { |cu| cu.conference }.last
        return redirect_to conference_home_path(conference_acronym: conference.acronym) if conference.present?
      end
      return redirect_to cfp_root_path
    end
    @versions = Version.where(conference_id: @conference.id).includes(:item).order("created_at DESC").limit(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%section
  .page-header
    %h1 Welcome
  .row
    .span16
      - if @conference.rooms.count == 0
        .blank-slate
          %p
            Welcome, you seem to have just created this
            conference. A good first step would be to go
            to the <em>Conference Settings</em> tab above
            and add a room to this conference. This will
            be needed to schedule your program.
      - if @conference.events.count == 0 and @conference.call_for_papers.nil?
        .blank-slate
          %p
            This conference does not yet have any events.
            (Note that throughout the application, the
            generic term 'event' is used to refer to all
            sessions within your conference, no matter if
            they are talks, workshops, panels or something
            else entirely).
          %p
            Start adding events by clicking on the 
            <em>Events</em> tab above. Or start a call for 
            papers, to allow others to submit events for
            you to review.
  - if can? :manage, CallForPapers           
    .row
      .span16
        %h2 
          Recent changes
          %small= link_to "more >>", recent_changes_path
        - if @versions.empty?
          .blank-slate
            %p
              Once you, or others start creating data for this
              conference, you will find who changed what here.
              This is especially interesting if you conduct a
              call for papers. In this case, this area allows
              you to quickly see if new submissions came in.
        - else
          = render "recent_changes/table"
          %p
  .row
    .span16
      %h2 Statistics
      - if @conference.events.count == 0
        .blank-slate
          %p
            Once you created some events for this conference,
            or gathered submissions through a call for papers,
            you will find some statistics about them here.
      - else
        %h4 Events by state
        %p
          = link_to "All", "#", :id => "events_all_types"
          |
          = link_to "lectures only", "#", :id => "events_lectures_only"
          |
          = link_to "workshops only", "#", :id => "events_workshops_only"
          |
          = link_to "others only", "#", :id => "events_others_only"
        #event_state_graph(style="width:600px;height:300px;")
        %table.zebra-stripe
          %thead
            %tr
              %th new
              %th review
              %th withdrawn
              %th unconfirmed
              %th confirmed
              %th canceled
              %th rejected
              %th total
          %tbody
            %tr
              %td= @conference.events.where(:state => :new).count
              %td= @conference.events.where(:state => :review).count
              %td= @conference.events.where(:state => :withdrawn).count
              %td= @conference.events.where(:state => :unconfirmed).count
              %td= @conference.events.where(:state => :confirmed).count
              %td= @conference.events.where(:state => :canceled).count
              %td= @conference.events.where(:state => :rejected).count
              %td= @conference.events.count
      - if @conference.languages.count > 1
        %h4 Events by language
        %p
          = link_to "All", "#", :id => "languages_all_events"
          |
          = link_to "Accepted only", "#", :id => "languages_accepted_events_only"
        #event_language_graph(style="width:400px;height:300px;")

      - if @conference.gender_breakdown.count > 1
        %h4 Events by gender
        %p
          = link_to "All", "#", :id => "gender_all_events"
          |
          = link_to "Accepted only", "#", :id => "gender_accepted_events_only"
        #event_gender_graph(style="width:400px;height:300px;")

:coffeescript
  update_languages_breakdown = (accepted_only = false) ->
    if accepted_only
      params = {"accepted_only": 1}
    else
      params = {}
    $.ajax(
      url: "#{language_breakdown_statistics_path}",
      type: "GET",
      dataType: "json",
      data: params,
      success: (data) ->
        $.plot($("#event_language_graph"), data, {series: {pie: {show: true}}})
    )
    
  update_gender_breakdown = (accepted_only = false) ->
    if accepted_only
      params = {"accepted_only": 1}
    else
      params = {}
    $.ajax(
      url: "#{gender_breakdown_statistics_path}",
      type: "GET",
      dataType: "json",
      data: params,
      success: (data) ->
        $.plot($("#event_gender_graph"), data, {series: {pie: {show: true}}})
    )

  update_events_breakdown = (type = "") ->
    if type
      params = {"type": type}
    else
      params = {}
    $.ajax(
      url: "#{events_by_state_statistics_path}",
      type: "GET",
      data: params,
      dataType: "json",
      success: (data) ->
        $.plot($("#event_state_graph"), data, {
          series: {
            bars: { show: true, barWidth: 1 }
          },
          xaxis: {
            ticks: [[0.5, "undecided"], [1.5,"accepted"], [2.5, "rejected"], [3.5, "withdrawn/canceled"]]
          }
        })
    )

  $ ->
    $("#events_all_types").click (event) ->
      update_events_breakdown()
    $("#events_lectures_only").click (event) ->
      update_events_breakdown("lectures")
    $("#events_workshops_only").click (event) ->
      update_events_breakdown("workshops")
    $("#events_others_only").click (event) ->
      update_events_breakdown("others")
    update_events_breakdown()

    $("#languages_all_events").click (event) ->
      update_languages_breakdown()
      event.preventDefault()
    $("#languages_accepted_events_only").click (event) ->
      update_languages_breakdown(true)
      event.preventDefault()
    update_languages_breakdown()

    $("#gender_all_events").click (event) ->
      update_gender_breakdown()
      event.preventDefault()
    $("#gender_accepted_events_only").click (event) ->
      update_gender_breakdown(true)
      event.preventDefault()
    update_gender_breakdown()