config/routes.rb
Frab::Application.routes.draw do

  scope "(:locale)" do

    resource :session

    match "/conferences/new" => "conferences#new", as: "new_conference"
    match "/conferences" => "conferences#create", as: "create_conference", via: :post
    match "/conferences" => "conferences#index", as: "conference_index", via: :get
    match "/conferences" => "conferences#destroy", via: :delete

    resources :people do
      resource :user
      member do
        put :attend
      end
    end

    scope path: "/:conference_acronym" do

      namespace :public do
        match "/schedule" => "schedule#index", as: "schedule_index"
        match "/schedule/style" => "schedule#style", as: "schedule_style"
        match "/schedule/:day" => "schedule#day", as: "schedule"
        match "/events" => "schedule#events", as: "events"
        match "/events/:id" => "schedule#event", as: "event"
        match "/speakers" => "schedule#speakers", as: "speakers"
        match "/speakers/:id" => "schedule#speaker", as: "speaker"

        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do

        resource :session

        resource :user do 
          resource :password
          resource :confirmation
        end

        resource :person do
          resource :availability
        end

        match "/events/:id/confirm/:token" => "events#confirm", as: "event_confirm_by_token"

        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end

        match "/open_soon" => "welcome#open_soon", as: "open_soon"
        match "/not_existing" => "welcome#not_existing", as: "not_existing"

        root to: "people#show"

      end # namespace :cfp

      match "/recent_changes" => "recent_changes#index", as: "recent_changes"

      match "/schedule.pdf" => "schedule#custom_pdf", as: "schedule_custom_pdf", defaults: {format: :pdf}
      match "/schedule" => "schedule#index", as: "schedule"
      match "/schedule/update_track" => "schedule#update_track", as: "schedule_update_track"
      match "/schedule/update_event" => "schedule#update_event", as: "schedule_update_event"
      match "/schedule/new_pdf" => "schedule#new_pdf", as: "new_schedule_pdf"
      match "/schedule/html_exports" => "schedule#html_exports"
      match "/schedule/create_static_export" => "schedule#create_static_export", via: :post
      match "/schedule/download_static_export" => "schedule#download_static_export"

      match "/statistics/events_by_state" => "statistics#events_by_state", as: "events_by_state_statistics"
      match "/statistics/language_breakdown" => "statistics#language_breakdown", as: "language_breakdown_statistics"
      match "/statistics/gender_breakdown" => "statistics#gender_breakdown", as: "gender_breakdown_statistics"

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
        get :edit_ticket_server
      end

      resource :call_for_papers do
        get :edit_notifications
      end
      match "/call_for_papers/default_notifications" => "call_for_papers#default_notifications", as: "call_for_papers_default_notifications"

      resources :people do
        resource :user
        resource :availability
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
        end
        resource :event_rating
        resources :event_feedbacks
      end

      match "/reports" => "reports#index", as: "reports"
      match "/reports/on_people/:id" => "reports#show_people", as: "report_on_people"
      match "/reports/on_events/:id" => "reports#show_events", as: "report_on_events"
      match "/reports/on_statistics/:id" => "reports#show_statistics", as: "report_on_statistics"

      resources :tickets do
        member do
          post :create
        end
      end

    end # scope path: "/:conference_acronym"

    match "/:conference_acronym" => "home#index", as: "conference_home"
    root to: "home#index"

  end # scope "(:locale)" do

  root to: "home#index"

end

app/models/call_for_papers.rb
class CallForPapers < ActiveRecord::Base

  belongs_to :conference
  has_many :notifications, dependent: :destroy

  accepts_nested_attributes_for :notifications, allow_destroy: true

  validates_presence_of :start_date, :end_date

  has_paper_trail

  def to_s
    "Call for Papers: #{self.conference.title}"
  end

end

app/controllers/call_for_papers_controller.rb
class CallForPapersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :not_submitter!
  load_and_authorize_resource

  def show
    @call_for_papers = @conference.call_for_papers
  end

  def new
    @call_for_papers = CallForPapers.new
  end

  def create
    @call_for_papers = CallForPapers.new(call_for_papers_params)
    @call_for_papers.conference = @conference

    if @call_for_papers.save
      redirect_to call_for_papers_path, notice: "Launched Call for Papers."
    else
      render action: "new"
    end
  end

  def edit
    @call_for_papers = @conference.call_for_papers
  end

  def edit_notifications
    @call_for_papers = @conference.call_for_papers
  end

  def update
    @call_for_papers = @conference.call_for_papers
    if @call_for_papers.update_attributes(call_for_papers_params)
      redirect_to call_for_papers_path, notice: "Changes saved successfully!"
    else
      flash[:alert] = "Failed to update notifications"
      render action: "edit"
    end
  end

  def default_notifications
    locale = params[:code]

    notification = Notification.new(locale: locale)
    notification.set_default_text(locale)

    respond_to do |format|
      format.json { render json: notification.to_json }
    end
  end

  private

  def call_for_papers_params
    params.require(:call_for_papers).permit(:start_date, :end_date, :hard_deadline, :welcome_text, :info_url, :contact_email, notifications_attributes: %i(id locale accept_subject accept_body reject_subject reject_body _destroy))
  end
end

app/helpers/call_for_papers_helper.rb
module CallForPapersHelper
  require 'securerandom'

  def available_locales(conference)
    codes = conference.language_codes
    codes | Person.involved_in(conference).map { |p| p.languages.all }.flatten.map{|l| l.code.downcase }
  end

  def get_uuid
    SecureRandom.uuid
  end

end

app/views/call_for_papers/_form.html.haml
= semantic_form_for @call_for_papers, :url => call_for_papers_path do |f|
  = f.inputs do
    = f.input :start_date, :hint => "Pick a date when your CfP should be open for the public."
    = f.input :end_date, :hint => "Pick a deadline for paper submission. This deadline will be displayed to the users but not otherwise enforced."
    = f.input :hard_deadline, :hint => "Pick a hard deadline. No paper submission will be possible after this date. Leave empty if you want to allow submissions indefinitely."
    = f.input :welcome_text, :hint => "Enter a welcome message or additional instructions you want to display to participants. (HTML)"
    = f.input :info_url, :hint => "A web page that contains additional information about the Call for Papers. Please enter a full URL including 'http://'"
    = f.input :contact_email, :hint => "An email address where participants can contact you in case they have any questions."
  = f.buttons do
    = f.commit_button :button_html => {:class => "btn primary"}

app/views/call_for_papers/_form_notifications.html.haml
- call_for_papers = @conference.call_for_papers
= semantic_form_for(call_for_papers, url: call_for_papers_path) do |f|
  = dynamic_association :notifications, t(:notifications), f
  = f.buttons do
    = f.commit_button :button_html => {:class => "btn primary"}

:javascript
  $(function() {

    NotificationDefaults = {

      fill: function(options) {
        var id     = options.id;
        var code = $('div#'+id+' select option:selected').text();
        NotificationDefaults._fetch(id, code);
      },

      _fetch: function(id, code) {
        $.ajax({
          type: "GET",
          dataType: "json",
          url: '#{ call_for_papers_default_notifications_path(conference_acronym: @conference.acronym) }', 
          data: {'code':code},
          success: function(result){
            var texts = result.notification;
            var topDiv = $('div#'+id);
            var inputs = topDiv.find('input[type=text]');
            $(inputs.get(0)).val(texts.accept_subject);
            $(inputs.get(1)).val(texts.reject_subject);
            inputs = topDiv.find('textarea');
            $(inputs.get(0)).val(texts.accept_body);
            $(inputs.get(1)).val(texts.reject_body);
          }
        });
      },

    };
  });

app/views/call_for_papers/_notification_fields.html.haml
- uuid = "nf#{get_uuid}"
%div{ :id => uuid }
  = f.inputs do
    = link_to_function "use default text", "NotificationDefaults.fill({ id: '#{uuid}' });", style: 'float:right'
    = f.input :locale, as: :select, collection: available_locales(@conference), hint: "Available locales for this conference and its speakers"
    = f.input "accept_subject", label: 'Accept subject'
    = f.input "accept_body",    label: 'Accept body', as: :text
    = f.input "reject_subject", label: 'Reject subject'
    = f.input "reject_body",    label: 'Reject body', as: :text
    = remove_association_link :notification, f

app/views/call_for_papers/edit.html.haml
%section
  .page-header
    %h1 Edit Call for Papers
  - if @conference.ticket_type == 'integrated'
    %ul.tabs
      %li.active= link_to "General", edit_call_for_papers_path
      %li= link_to "Notification text", edit_notifications_call_for_papers_path

  .row
    .span16
      = render "form"

app/views/call_for_papers/edit_notifications.html.haml
%section
  .page-header
    %h1 Edit Call for Papers

  - if @conference.ticket_type == 'integrated'
    %ul.tabs
      %li= link_to "General", edit_call_for_papers_path
      %li.active= link_to "Notification text", edit_notifications_call_for_papers_path

  .row
    .span6
      %h2 Possible variables
      %dl.dl-horizontal
        - Notification::VARIABLES.each do |key, desc|
          %dt= "#{desc}:"
          %dd= "%{#{key}}"

    .span16
      = render "form_notifications"

app/views/call_for_papers/new.html.haml
%section
  .page-header
    %h1 Launch a Call for Papers
  .row
    .span16
      = render "form"

app/views/call_for_papers/show.html.haml
%section
  .page-header
    .pull-right
      - if can? :manage, CallForPapers
        = action_button "primary", "Edit", edit_call_for_papers_path, :hint => "Edit this call for paper's data."
        - if @conference.ticket_type == 'integrated'
          = action_button "primary", "Edit Notifications", edit_notifications_call_for_papers_path, :hint => "Edit email notififaction templates."
    %h1 Call for Papers
  - if @conference.call_for_papers.welcome_text
    .row
      .span16
        %p
          = simple_format @conference.call_for_papers.welcome_text
  - if @conference.call_for_papers.start_date
    .row
      .span16
        %p The call for papers starts at #{l(@conference.call_for_papers.start_date)} and ends at #{l(@conference.call_for_papers.end_date)}.
  .row
    .span16
      %p
        The interface for submitters is available at:
        = new_cfp_session_url
  .row
    .span16
      #submission_graph{:style => "width: 800px; height: 300px;"}

  .row
    .span16
      #submission_graph-sum_to_submission_time{:style => "width: 800px; height: 300px;"}
        
:javascript
  var data = #{@conference.submission_data.inspect};
  
  $.plot($("#submission_graph"), [data], { xaxis: { mode: "time" } });
  $.plot($("#submission_graph-sum_to_submission_time"), [data.reduce(function (a,b) {

    return a.concat([[
      b[0],
      b[1]+a[a.length-1][1]
    ]])
  }, [[0,0]]).slice(1)], { xaxis: { mode: "time" } });