config/routes.rb
Frab::Application.routes.draw do

  scope "(:locale)" do

    resource :session

    match "/conferences/new" => "conferences#new", as: "new_conference"
    match "/conferences" => "conferences#create", as: "create_conference", via: :post
    match "/conferences" => "conferences#index", as: "conference_index", via: :get
    match "/conferences" => "conferences#destroy", via: :delete

    resources :people do
      resource :user
      member do
        put :attend
      end
    end

    scope path: "/:conference_acronym" do

      namespace :public do
        match "/schedule" => "schedule#index", as: "schedule_index"
        match "/schedule/style" => "schedule#style", as: "schedule_style"
        match "/schedule/:day" => "schedule#day", as: "schedule"
        match "/events" => "schedule#events", as: "events"
        match "/events/:id" => "schedule#event", as: "event"
        match "/speakers" => "schedule#speakers", as: "speakers"
        match "/speakers/:id" => "schedule#speaker", as: "speaker"

        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do

        resource :session

        resource :user do 
          resource :password
          resource :confirmation
        end

        resource :person do
          resource :availability
        end

        match "/events/:id/confirm/:token" => "events#confirm", as: "event_confirm_by_token"

        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end

        match "/open_soon" => "welcome#open_soon", as: "open_soon"
        match "/not_existing" => "welcome#not_existing", as: "not_existing"

        root to: "people#show"

      end # namespace :cfp

      match "/recent_changes" => "recent_changes#index", as: "recent_changes"

      match "/schedule.pdf" => "schedule#custom_pdf", as: "schedule_custom_pdf", defaults: {format: :pdf}
      match "/schedule" => "schedule#index", as: "schedule"
      match "/schedule/update_track" => "schedule#update_track", as: "schedule_update_track"
      match "/schedule/update_event" => "schedule#update_event", as: "schedule_update_event"
      match "/schedule/new_pdf" => "schedule#new_pdf", as: "new_schedule_pdf"
      match "/schedule/html_exports" => "schedule#html_exports"
      match "/schedule/create_static_export" => "schedule#create_static_export", via: :post
      match "/schedule/download_static_export" => "schedule#download_static_export"

      match "/statistics/events_by_state" => "statistics#events_by_state", as: "events_by_state_statistics"
      match "/statistics/language_breakdown" => "statistics#language_breakdown", as: "language_breakdown_statistics"
      match "/statistics/gender_breakdown" => "statistics#gender_breakdown", as: "gender_breakdown_statistics"

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
        get :edit_ticket_server
      end

      resource :call_for_papers do
        get :edit_notifications
      end
      match "/call_for_papers/default_notifications" => "call_for_papers#default_notifications", as: "call_for_papers_default_notifications"

      resources :people do
        resource :user
        resource :availability
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
        end
        resource :event_rating
        resources :event_feedbacks
      end

      match "/reports" => "reports#index", as: "reports"
      match "/reports/on_people/:id" => "reports#show_people", as: "report_on_people"
      match "/reports/on_events/:id" => "reports#show_events", as: "report_on_events"
      match "/reports/on_statistics/:id" => "reports#show_statistics", as: "report_on_statistics"

      resources :tickets do
        member do
          post :create
        end
      end

    end # scope path: "/:conference_acronym"

    match "/:conference_acronym" => "home#index", as: "conference_home"
    root to: "home#index"

  end # scope "(:locale)" do

  root to: "home#index"

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :not_submitter!

  def index
  end

  def show_events
    authorize! :manage, CallForPapers

    @report_type = params[:id]
    @events = []
    @search_count = 0

    conference_events = @conference.events
    if params[:term]
        conference_events = @conference.events.with_query(params[:term])
    end

    case @report_type
    when 'lectures_with_speaker'
      r = conference_events.with_speaker.where(event_type: :lecture)
    when 'lectures_not_confirmed'
      r = conference_events.with_speaker.where(event_type: :lecture, state: [:new,:review] )
      when 'events_not_public'
      r = conference_events.where(public: false)
    when 'events_that_are_workshops'
      r = conference_events.where(Event.arel_table[:event_type].eq(:workshop))
    when 'event_timeslot_deviation'
      r = conference_events.where(event_type: :lecture).where('time_slots != ?', @conference.default_timeslots)
    when 'events_that_are_no_lectures'
      r = conference_events.where(Event.arel_table[:event_type].not_eq(:lecture).and(Event.arel_table[:event_type].not_eq(:workshop)))
    when 'events_without_speaker'
      r = conference_events.without_speaker
    when 'unconfirmed_events'
      r = conference_events.where(event_type: :lecture, state: :unconfirmed)
    when 'events_with_a_note'
      r = conference_events.where(Event.arel_table[:note].not_eq("").or(Event.arel_table[:submission_note].not_eq("")))
    when 'events_with_unusual_state_speakers'
      r = conference_events.joins(:event_people).where(event_people: { role_state: [:canceled, :declined, :idea, :offer, :unclear], event_role: [:moderator, :speaker] } )
    when 'do_not_record_events'
      r = conference_events.where(:do_not_record => true)
    end

    unless r.nil? or r.empty?
      @search = r.search(params[:q])
      @search_count = r.count
      @events = @search.result.paginate page: page_param
    end
    render :show
  end

  def show_people
    authorize! :manage, CallForPapers

    @report_type = params[:id]
    @people = []
    @search_count = 0

    conference_people = Person
    if params[:term]
        conference_people = Person.with_query(params[:term])
    end

    case @report_type
    when 'expected_speakers'
      r = Person.joins(events: :conference).
        where(:'conferences.id' => @conference.id).
        where(:'event_people.event_role' => ['speaker', 'moderator']).
        where(:'event_people.role_state' => 'confirmed').
        where(:'events.public' => true).
        where('events.start_time > ?', Time.now).
        where('events.start_time < ?', Time.now.since(4.hours)).
        where(:'events.state' => ['unconfirmed', 'confirmed']).order('events.start_time ASC').group(:'people.id')
    when 'people_speaking_at'
      r = conference_people.speaking_at(@conference)
    when 'people_with_a_note'
      r = conference_people.involved_in(@conference).where(Person.arel_table[:note].not_eq(""))
    when 'people_with_more_than_one'
      r = conference_people.involved_in(@conference).where("event_people.event_role" => ["submitter"]).group('event_people.person_id').having('count(*) > 1')
    end

    unless r.nil? or r.empty?
      @search = r.search(params[:q])
      @search_count = r.length
      @people = @search.result.paginate page: page_param
    end
    render :show
  end

  def show_statistics
    authorize! :manage, CallForPapers

    @report_type = params[:id]
    @search_count = 0

    case @report_type
    when 'confirmed_events_by_track'
      @data = []
      row = []
      @labels = @conference.tracks.collect { |t| t.name }
      @labels.each { |track|
        row << @conference.events.confirmed.joins(:track).where(tracks: { name: track}).count
      }
      @data << row
      @search_count = row.inject(:+)

    when 'events_by_track'
      @data = []
      row = []
      @labels = @conference.tracks.collect { |t| t.name }
      @labels.each { |track|
        row << @conference.events.candidates.joins(:track).where(tracks: { name: track}).count
      }
      @data << row
      @search_count = row.inject(:+)

    when 'event_timeslot_sum'
      @data = []
      row = []
      @labels = %w{LecturesCommited LecturesConfirmed LecturesUnconfirmed Lectures Workshops}
      events = @conference.events.where(event_type: :lecture, state: [:confirmed, :unconfirmed])
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :lecture, state: :confirmed)
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :lecture, state: :unconfirmed)
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :lecture)
      row << @conference.event_duration_sum(events)
      events = @conference.events.where(event_type: :workshops)
      row << @conference.event_duration_sum(events)
      @data << row
      @search_count = nil

    when 'people_speaking_by_day'
      @data = []
      row = []
      @labels = %w{Day FullName PublicName Email Event Role State} # TODO translate

      @conference.days.each do |day|
        @conference.events.confirmed.no_conflicts.public.scheduled_on(day).order(:start_time).each do |event|
          event.event_people.presenter.each do |event_person|
            person = event_person.person
            row = [ l(day.date), person.full_name, person.public_name, person.email, event.title, event_person.event_role, event_person.role_state ]
            @data << row
          end
        end
      end

      @search_count = nil
    end

    render :show
  end

end

app/views/reports/_events_table.html.haml
%table.zebra-stripe
  %thead
    %tr
      %th.first
      - if @search
        %th= sort_link @search, :title, "Title", :term => params[:term]
        %th= sort_link @search, :track_name, "Track", :term => params[:term]
        %th= sort_link @search, :event_type, :term => params[:term]
        %th= sort_link @search, :state, "State", :term => params[:term]
        %th= sort_link @search, :created_at, :term => params[:term]
      - else
        %th Title
        %th Track
        %th Event type
        %th State
        %th Created at
      %th
  %tbody
    - events.each do |event|
      %tr
        %td= link_to (image_box event.logo, :small), event
        %td
          = link_to event.title, event
          %p.small
            = by_speakers(event)
        %td= event.track.try(:name)
        %td= event.event_type
        %td= event.state
        %td= l(event.created_at.to_date)
        %td.buttons
          = action_button "small", 'Show', event
          - if can? :manage, event
            = action_button "small", 'Edit', edit_event_path(event)
            = action_button "small danger", 'Destroy', event, :confirm => 'Are you sure?', :method => :delete

app/views/reports/_people_table.html.haml
%table.zebra-stripe
  %thead
    %tr
      %th.first
      - if @search
        %th= sort_link @search, :full_name, :term => params[:term]
        %th= sort_link @search, :public_name, :term => params[:term]
        %th= sort_link @search, :email, :term => params[:term]
        %th Events in
        %th= sort_link @search, :created_at, :term => params[:term]
      - else
        %th Full name
        %th Public name
        %th Email
        %th Events in
        %th Created at
      %th.last
  %tbody
    - @people.each do |person|
      %tr
        %td= link_to (image_box person.avatar, :small), person
        %td= link_to person.full_name, person
        %td
          -unless person.public_name.nil?
            = link_to person.public_name, person
        %td= link_to person.email, person
        %td= person.events_in(@conference).map{|e| link_to e.title, e}.join(', ').html_safe
        %td= l(person.created_at.to_date)
        %td.buttons
          = action_button "small", 'Show', person
          - if can? :manage, person
            = action_button "small", 'Edit', edit_person_path(person)
            = action_button "small danger", 'Destroy', person, :confirm => 'Are you sure?', :method => :delete

app/views/reports/_report_menu.html.haml
%p Query Events
%ul
  %li= link_to "lectures with speaker", report_on_events_path('lectures_with_speaker')
  %li= link_to "lectures that are new or review", report_on_events_path('lectures_not_confirmed')
  %li= link_to "events that are unconfirmed", report_on_events_path("unconfirmed_events")
  %li= link_to "events that are not public", report_on_events_path("events_not_public")
  %li= link_to "list of all workshops", report_on_events_path('events_that_are_workshops')
  %li= link_to "events that are neither lectures nor workshops", report_on_events_path('events_that_are_no_lectures')
  %li= link_to "events with a note", report_on_events_path('events_with_a_note')
  %li= link_to "events without speaker", report_on_events_path('events_without_speaker')
  %li= link_to "events with speakers in a problematic state", report_on_events_path("events_with_unusual_state_speakers")
  %li= link_to "events with 'do not record' flag set", report_on_events_path("do_not_record_events")
  %li= link_to "list all lectures with non default timeslots", report_on_events_path('event_timeslot_deviation')
%p Query Speakers  
%ul
  %li= link_to "missing speakers for the next 4 hours", report_on_people_path("expected_speakers")
  %li= link_to "confirmed people speaking at conference", report_on_people_path("people_speaking_at")
  %li= link_to "people with a note in their submission", report_on_people_path("people_with_a_note")
  %li= link_to "people with more than one submission", report_on_people_path("people_with_more_than_one")
%p Statistics
%ul
  %li= link_to "used timeslots (hours)", report_on_statistics_path("event_timeslot_sum")
  %li= link_to "confirmed event numbers by track", report_on_statistics_path("confirmed_events_by_track")
  %li= link_to "event numbers by track", report_on_statistics_path("events_by_track")
  %li= link_to "confirmed speakers by day with attendance status", report_on_statistics_path("people_speaking_by_day")

app/views/reports/_statistics_table.html.haml
%table.zebra-stripe
  %thead
    %tr
    - @labels.each do |label|
      %th= label
  %tbody
    - @data.each do |row|
      %tr
      - row.each do |c|
        %td= c

app/views/reports/index.html.haml
%section
  .page-header
    %h1 Available Reports
  = render 'report_menu'

app/views/reports/show.html.haml
%section
  .page-header
    %h1 Available Reports
  = render 'report_menu'
  %h2 Results
  - if @people or @events
    = render 'shared/simple_search', :path => request.path
  - unless @search_count.nil?
    Found 
    = @search_count
    results.
  - if not @people.nil? and not @people.empty?
    .row
      .span16
        - if @people.all.empty?
          %p Sorry, but your search yielded no results.
        - else  
          = render 'people_table', :people => @people 
          = actions_bar do
            = will_paginate @people
  - if not @events.nil? and not @events.empty?
    .row
      .span16
        - if @events.all.empty?
          %p Sorry, but your search yielded no results.
        - else  
          = render 'events_table', :events => @events 
          = actions_bar do
            = will_paginate @events
  - if not @data.nil? and not @data.empty?
    .row
      .span16
        = render 'statistics_table', :data => @data 